print("Today's Date?")
date = input()
print("Breakfast Calories?")
breakfast = int(input())
print("Lunch Calories?")
lunch = int(input())
print("Dinner Calories?")
dinner = int(input())
print("Snack Calories?")
snack = int(input())
print("Calorie content for " + date + ": " + str(breakfast + lunch + dinner + snack) + " calories")